run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert

linters-settings:
  errcheck:
    # Don't check for unchecked errors in test files
    exclude-functions:
      - (io.Closer).Close
      - (*os.File).Close

issues:
  exclude-rules:
    # Test files - don't check error returns (common in test setup/teardown)
    - path: _test\.go
      linters:
        - errcheck
    # Defer cleanup functions often ignore errors intentionally
    - source: "defer.*Close"
      linters:
        - errcheck
    # Allow unused fields in TUI model (may be used later or for future features)
    - path: internal/tui/model\.go
      linters:
        - unused
